- name: Enable php 7.4
  shell: yum-config-manager --enable remi-php74
  when: php_version == 74

- name: Enable php 7.3
  shell: yum-config-manager --enable remi-php73
  when: php_version == 73

- name: Enable php 7.2
  shell: yum-config-manager --enable remi-php72
  when: php_version == 72

- name: Install php
  yum:
    name: "{{ php_packages }}"