- name: install the latest version of Apache
  yum:
    name: "{{ package }}"
    state: latest

- name: Start service httpd, if not started
  service:
    name: "{{ package }}"
    state: started
    enabled: yes