- hosts: all
  become: yes          # becoming sudo = access permission 
  tasks:
  - hostname:
      name: "{{ inventory_hostname }}"
  - debug: 
      msg: "{{ ansible_distribution }}"
  - name: Install Apache
    include_tasks: "{{ ansible_distribution }}.yml"

